//GameMode_Prop_Hunt slayer config
if(isObject(%mini))
	%mini.preConfigLoad("config/server/Slayer/config_last.cs");

//PREFERENCES //USAGE: (category,title,value)
Slayer.Prefs.setPref("Server","Announcements","",%mini);
Slayer.Prefs.setPref("Teams","Ally Same Colors","0",%mini);
Slayer.Prefs.setPref("Teams","Auto Sort","1",%mini);
Slayer.Prefs.setPref("Teams","Balance New Teams","1",%mini);
Slayer.Prefs.setPref("Teams","Balance Teams","0",%mini);
Slayer.Prefs.setPref("Teams","Display Join/Leave Messages","1",%mini);
Slayer.Prefs.setPref("Teams","Friendly Fire","0",%mini);
Slayer.Prefs.setPref("Teams","Lock Teams","1",%mini);
Slayer.Prefs.setPref("Teams","Punish Friendly Fire","1",%mini);
Slayer.Prefs.setPref("Teams","Rounds Between Shuffle","1",%mini);
Slayer.Prefs.setPref("Teams","Shuffle Teams","1",%mini);
Slayer.Prefs.setPref("Teams","Shuffle Mode","0",%mini);
Slayer.Prefs.setPref("Teams","Team-Only DeadCam","0",%mini);
Slayer.Prefs.setPref("Teams","Max Teams","100",%mini);
Slayer.Prefs.setPref("Chat","Allow Dead Talking","1",%mini);
Slayer.Prefs.setPref("Chat","Death Message Mode","0",%mini);
Slayer.Prefs.setPref("Chat","Enable Team Chat","1",%mini);
Slayer.Prefs.setPref("Chat","Team Display Mode","2",%mini);
Slayer.Prefs.setPref("Damage","Bot","1",%mini);
Slayer.Prefs.setPref("Damage","Brick","1",%mini);
Slayer.Prefs.setPref("Damage","Falling","1",%mini);
Slayer.Prefs.setPref("Damage","Self","1",%mini);
Slayer.Prefs.setPref("Damage","Vehicle","1",%mini);
Slayer.Prefs.setPref("Damage","Weapon","1",%mini);
Slayer.Prefs.setPref("EoRR","Display End of Round Report","1",%mini);
Slayer.Prefs.setPref("EoRR","Display Team Scores","1",%mini);
Slayer.Prefs.setPref("Minigame","Allow Movement During Reset","0",%mini);
Slayer.Prefs.setPref("Minigame","Clear Scores on Reset","0",%mini);
Slayer.Prefs.setPref("Minigame","Clear Stats on Reset","1",%mini);
Slayer.Prefs.setPref("Minigame","Custom Rule","",%mini);
Slayer.Prefs.setPref("Minigame","Default Minigame","1",%mini);
Slayer.Prefs.setPref("Minigame","Enable Building","0",%mini);
Slayer.Prefs.setPref("Minigame","Enable Painting","0",%mini);
Slayer.Prefs.setPref("Minigame","Enable Wand","0",%mini);
Slayer.Prefs.setPref("Minigame","Gamemode","TSlyr",%mini);
Slayer.Prefs.setPref("Minigame","Host Name","HOST",%mini);
Slayer.Prefs.setPref("Minigame","Invite-Only","0",%mini);
Slayer.Prefs.setPref("Minigame","Late Join Time","0",%mini);
Slayer.Prefs.setPref("Minigame","Players Use Own Bricks","0",%mini);
Slayer.Prefs.setPref("Minigame","Pre-Round Countdown","0",%mini);
Slayer.Prefs.setPref("Minigame","Spawn Brick Color","-1",%mini);
Slayer.Prefs.setPref("Minigame","Time Between Rounds","10",%mini);
Slayer.Prefs.setPref("Minigame","Title","Creeper",%mini);
Slayer.Prefs.setPref("Minigame","Use All Players' Bricks","1",%mini);
Slayer.Prefs.setPref("Minigame","Use Spawn Bricks","1",%mini);
Slayer.Prefs.setPref("Permissions","Create Minigame Rights","2",%mini);
Slayer.Prefs.setPref("Permissions","Edit Rights","3",%mini);
Slayer.Prefs.setPref("Permissions","Leave Rights","2",%mini);
Slayer.Prefs.setPref("Permissions","Reset Rights","3",%mini);
Slayer.Prefs.setPref("Player","Name Distance","140",%mini);
Slayer.Prefs.setPref("Player","Playertype",nameToID(PlayerNoJet),%mini);
Slayer.Prefs.setPref("Player","Starting Equipment 0",0,%mini);
Slayer.Prefs.setPref("Player","Starting Equipment 1",0,%mini);
Slayer.Prefs.setPref("Player","Starting Equipment 2",0,%mini);
Slayer.Prefs.setPref("Player","Starting Equipment 3",0,%mini);
Slayer.Prefs.setPref("Player","Starting Equipment 4",0,%mini);
Slayer.Prefs.setPref("Points","Break Brick","0",%mini);
Slayer.Prefs.setPref("Points","CP Capture","10",%mini);
Slayer.Prefs.setPref("Points","Die","0",%mini);
Slayer.Prefs.setPref("Points","Friendly Fire","-5",%mini);
Slayer.Prefs.setPref("Points","Kill Bot","0",%mini);
Slayer.Prefs.setPref("Points","Kill Player","0",%mini);
Slayer.Prefs.setPref("Points","Plant Brick","0",%mini);
Slayer.Prefs.setPref("Points","Suicide","0",%mini);
Slayer.Prefs.setPref("Respawn Time","Bot","5",%mini);
Slayer.Prefs.setPref("Respawn Time","Brick","30",%mini);
Slayer.Prefs.setPref("Respawn Time","Friendly Fire Penalty","5",%mini);
Slayer.Prefs.setPref("Respawn Time","Player","5",%mini);
Slayer.Prefs.setPref("Respawn Time","Vehicle","10",%mini);
Slayer.Prefs.setPref("Victory Method","Lives","0",%mini);
Slayer.Prefs.setPref("Victory Method","Points","0",%mini);
Slayer.Prefs.setPref("Victory Method","Time","0",%mini);
Slayer.Prefs.setPref("Capture Points","Tick Time","150",%mini);
Slayer.Prefs.setPref("Capture Points","Use Transitional Colors","1",%mini);
Slayer.Prefs.setPref("Events","Restrict Output Events","1",%mini);
Slayer.Prefs.setPref("Fly-Through Cam","Play At Beginning of Round","1",%mini);
Slayer.Prefs.setPref("Fly-Through Cam","Countdown During Fly-Thru","0",%mini);
Slayer.Prefs.setPref("Fly-Through Cam","Rounds Between Fly-Thrus","0",%mini);
Slayer.Prefs.setPref("Bonus Kills","Enable","1",%mini);
Slayer.Prefs.setPref("Bonus Kills","Kill Spree Start","5",%mini);
Slayer.Prefs.setPref("Bonus Kills","Bonus Kill Points","1",%mini);
Slayer.Prefs.setPref("Giants","Giant Size","5",%mini);

//TEAMS
if(isObject(%mini.Teams))
{
	%team = %mini.Teams.addTeam();
		%mini.TeamPrefs.setPref(%team,"Chat","Enable Team Chat","1");
		%mini.TeamPrefs.setPref(%team,"Chat","Name Color","");
		%mini.TeamPrefs.setPref(%team,"Team","Auto Sort Weight","1");
		%mini.TeamPrefs.setPref(%team,"Team","Auto Sort","1");
		%mini.TeamPrefs.setPref(%team,"Team","Color","14");
		%mini.TeamPrefs.setPref(%team,"Team","Lives","-1");
		%mini.TeamPrefs.setPref(%team,"Team","Lock Team","0");
		%mini.TeamPrefs.setPref(%team,"Team","Max Players","-1");
		%mini.TeamPrefs.setPref(%team,"Team","Name","The Players");
		%mini.TeamPrefs.setPref(%team,"Team","Player Scale","1");
		%mini.TeamPrefs.setPref(%team,"Team","Playertype",nameToID(PlayerNoJet));
		%mini.TeamPrefs.setPref(%team,"Team","Respawn Time","-1");
		%mini.TeamPrefs.setPref(%team,"Team","Start Equip 0");
		%mini.TeamPrefs.setPref(%team,"Team","Start Equip 1");
		%mini.TeamPrefs.setPref(%team,"Team","Start Equip 2",0);
		%mini.TeamPrefs.setPref(%team,"Team","Start Equip 3",0);
		%mini.TeamPrefs.setPref(%team,"Team","Start Equip 4",0);
		%mini.TeamPrefs.setPref(%team,"Team","Uni Update Trigger","0");
		%mini.TeamPrefs.setPref(%team,"Team","Uniform","0");
		%mini.TeamPrefs.setPref(%team,"Team","Win on Time Up","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","Accent","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","AccentColor","0.900 0.900 0.900 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","Chest","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","ChestColor","");
		%mini.TeamPrefs.setPref(%team,"Uniform","DecalColor","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","DecalName","base/data/shapes/player/decals/AAA-None.png");
		%mini.TeamPrefs.setPref(%team,"Uniform","FaceColor","49");
		%mini.TeamPrefs.setPref(%team,"Uniform","FaceName","Add-Ons/Face_Default/memeCats.png");
		%mini.TeamPrefs.setPref(%team,"Uniform","Hat","1");
		%mini.TeamPrefs.setPref(%team,"Uniform","HatColor","0.900 0.900 0.900 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","HeadColor","1 0.878431 0.611765 1");
		%mini.TeamPrefs.setPref(%team,"Uniform","Hip","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","HipColor","0.900 0.900 0.900 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","LArm","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","LArmColor","0.900 0.900 0.900 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","LHand","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","LHandColor","0.750 0.750 0.750 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","LLeg","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","LLegColor","0.750 0.750 0.750 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","Pack","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","PackColor","0.750 0.750 0.750 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","RArm","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","RArmColor","0.900 0.900 0.900 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","RHand","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","RHandColor","0.750 0.750 0.750 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","RLeg","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","RLegColor","0.750 0.750 0.750 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","SecondPack","6");
		%mini.TeamPrefs.setPref(%team,"Uniform","SecondPackColor","0.750 0.750 0.750 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","TorsoColor","0.900 0.900 0.900 1.000");
	%team = %mini.Teams.addTeam(); // the creeper team is usually kept empty except in That Bastard and Karoshi
		%mini.TeamPrefs.setPref(%team,"Chat","Enable Team Chat","1");
		%mini.TeamPrefs.setPref(%team,"Chat","Name Color","");
		%mini.TeamPrefs.setPref(%team,"Team","Auto Sort Weight","0");
		%mini.TeamPrefs.setPref(%team,"Team","Auto Sort","1");
		%mini.TeamPrefs.setPref(%team,"Team","Color","8");
		%mini.TeamPrefs.setPref(%team,"Team","Lives","-1");
		%mini.TeamPrefs.setPref(%team,"Team","Lock Team","0");
		%mini.TeamPrefs.setPref(%team,"Team","Max Players","-1");
		%mini.TeamPrefs.setPref(%team,"Team","Name","The Creeper");
		%mini.TeamPrefs.setPref(%team,"Team","Player Scale","1");
		%mini.TeamPrefs.setPref(%team,"Team","Playertype",nameToID(PlayerNoJet));
		%mini.TeamPrefs.setPref(%team,"Team","Respawn Time","-1");
		%mini.TeamPrefs.setPref(%team,"Team","Start Equip 0",0);
		%mini.TeamPrefs.setPref(%team,"Team","Start Equip 1",0);
		%mini.TeamPrefs.setPref(%team,"Team","Start Equip 2",0);
		%mini.TeamPrefs.setPref(%team,"Team","Start Equip 3",0);
		%mini.TeamPrefs.setPref(%team,"Team","Start Equip 4",0);
		%mini.TeamPrefs.setPref(%team,"Team","Uni Update Trigger","811232");
		%mini.TeamPrefs.setPref(%team,"Team","Uniform","0");
		%mini.TeamPrefs.setPref(%team,"Team","Win on Time Up","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","Accent","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","AccentColor","0.898039 0.000000 0.000000 1.000000");
		%mini.TeamPrefs.setPref(%team,"Uniform","Chest","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","ChestColor","");
		%mini.TeamPrefs.setPref(%team,"Uniform","DecalColor","6");
		%mini.TeamPrefs.setPref(%team,"Uniform","DecalName","Add-Ons/Decal_Jirue/DrKleiner.png");
		%mini.TeamPrefs.setPref(%team,"Uniform","FaceColor","18");
		%mini.TeamPrefs.setPref(%team,"Uniform","FaceName","Add-Ons/Face_Jirue/KleinerSmiley.png");
		%mini.TeamPrefs.setPref(%team,"Uniform","Hat","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","HatColor","0.898039 0.000000 0.000000 1.000000");
		%mini.TeamPrefs.setPref(%team,"Uniform","HeadColor","1 0.878431 0.611765 1");
		%mini.TeamPrefs.setPref(%team,"Uniform","Hip","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","HipColor","0.200 0.200 0.200 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","LArm","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","LArmColor","0.105882 0.458824 0.768627 1");
		%mini.TeamPrefs.setPref(%team,"Uniform","LHand","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","LHandColor","1 0.878431 0.611765 1");
		%mini.TeamPrefs.setPref(%team,"Uniform","LLeg","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","LLegColor","0.200 0.200 0.200 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","Pack","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","PackColor","0.898039 0.000000 0.000000 1.000000");
		%mini.TeamPrefs.setPref(%team,"Uniform","RArm","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","RArmColor","0.105882 0.458824 0.768627 1");
		%mini.TeamPrefs.setPref(%team,"Uniform","RHand","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","RHandColor","1 0.878431 0.611765 1");
		%mini.TeamPrefs.setPref(%team,"Uniform","RLeg","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","RLegColor","0.200 0.200 0.200 1.000");
		%mini.TeamPrefs.setPref(%team,"Uniform","SecondPack","0");
		%mini.TeamPrefs.setPref(%team,"Uniform","SecondPackColor","0.898039 0.000000 0.000000 1.000000");
		%mini.TeamPrefs.setPref(%team,"Uniform","TorsoColor","0.105882 0.458824 0.768627 1");
}

if(isObject(%mini))
	%mini.postConfigLoad("config/server/Slayer/config_last.cs");
